name: CI
on:
  pull_request:
    branches:
      - master
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    env: 
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.8"
    - name: Build and Test
      run: sbt -v -Dfile.encoding=UTF-8 +test
  publish-gpr:
    needs: test
    username: StefanosTouf
    password: ${{ secrets.GITHUB_TOKEN }}
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v1
      - run: sbt publish
 